name: voucher-wallet
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - psycopg2=2.9.3
  - pip:
      - django==4.1.5
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.2.2
      - pillow==9.4.0
      - drf-yasg==1.21.4
      - flake8==6.0.0
      - gunicorn==20.1.0
      - django-cors-headers==3.13.0
