# Generated by Django 4.1.5 on 2023-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('customerProfile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='preferences',
            field=models.ManyToManyField(related_name='selected_by', to='tag.tag'),
        ),
    ]
