# Generated by Django 4.1.5 on 2023-02-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerProfile', '0001_initial'),
        ('shopProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('times_used', models.IntegerField(blank=True, null=True)),
                ('customer_profiles', models.ManyToManyField(related_name='coupons_owned', to='customerProfile.customerprofile')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_created', to='shopProfile.shopprofile')),
            ],
        ),
    ]
