# Generated by Django 4.1.5 on 2023-02-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('times_redeemed', models.IntegerField(default=0)),
                ('redeem_limit', models.IntegerField(default=0)),
                ('discount_type', models.CharField(choices=[('value', 'Value'), ('percentage', 'Percentage')], default='percentage', max_length=10)),
                ('discount', models.FloatField(default=0)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='EUR', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('has_been_used', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='coupon.coupon')),
            ],
        ),
    ]
