# Generated by Django 4.1.5 on 2023-02-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        ('customerProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='customerProfile.customerprofile'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer_profiles',
            field=models.ManyToManyField(blank=True, related_name='coupons_owned', to='customerProfile.customerprofile'),
        ),
    ]
