# Generated by Django 4.1.5 on 2023-02-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('shopProfile', '0001_initial'),
        ('coupon', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_created', to='shopProfile.shopprofile'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_tag', to='tag.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='couponcode',
            unique_together={('coupon', 'customer_profile')},
        ),
    ]
