# Generated by Django 4.1.5 on 2023-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_customer_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
