# Generated by Django 4.1.5 on 2023-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopProfile', '0001_initial'),
        ('customerProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('customers_tagging', models.ManyToManyField(blank=True, related_name='preferences', to='customerProfile.customerprofile')),
                ('shops_tagged', models.ManyToManyField(blank=True, related_name='tags', to='shopProfile.shopprofile')),
            ],
        ),
    ]
