# Generated by Django 4.1.5 on 2023-02-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customerProfile', '0001_initial'),
        ('shopProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('customers_tagging', models.ManyToManyField(blank=True, null=True, related_name='customers_tagged',
                                                             to='customerProfile.customerprofile')),
                ('shops_tagged', models.ManyToManyField(blank=True, null=True, related_name='shops_tagged',
                                                        to='shopProfile.shopprofile')),
            ],
        ),
    ]
