# Generated by Django 4.1.5 on 2023-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='customers_tagging',
            field=models.ManyToManyField(blank=True, null=True, related_name='preferences', to='customerProfile.customerprofile'),
        ),
    ]
