# Generated by Django 4.1.5 on 2023-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='shops_tagged',
        ),
        migrations.AddField(
            model_name='tag',
            name='coupons_tagged',
            field=models.ManyToManyField(blank=True, related_name='tags', to='coupon.coupon'),
        ),
    ]
